CREATE DATABASE TRUONGHOC1;
USE TRUONGHOC1;

CREATE TABLE TRUONG (
    MATR INT,
    TENTR VARCHAR(50),
    DIACHITR VARCHAR(100),
    PRIMARY KEY (MATR)
);

CREATE TABLE HS (
    MAHS VARCHAR(50),
    HO VARCHAR(50),
    TEN VARCHAR(50),
    CCCD VARCHAR(50),
    NTNS VARCHAR(50),
    DCHI_HS VARCHAR(100),
    PRIMARY KEY (MAHS)
);

CREATE TABLE HOC (
    MATR INT,
    MAHS VARCHAR(50),
    NAMHOC INT,
    DIEMTB DECIMAL,
    XEPLOAI VARCHAR(50),
    KETQUA VARCHAR(50),
    PRIMARY KEY (MATR, MAHS, NAMHOC),
    FOREIGN KEY (MATR) REFERENCES TRUONG(MATR),
    FOREIGN KEY (MAHS) REFERENCES HS(MAHS)
);
